CJ_IMayFly_home:
    path:   /{page}
    defaults:
        _controller: CJIMayFlyBundle:Post:index
        page: 1
    requirements:
        page: \d+


CJ_IMayFly_view:
    path:   /post/{id}
    defaults:
        _controller: CJIMayFlyBundle:Post:view
        id: 1
    requirements:
        id: \d+

CJ_IMayFly_add:
    path:   /add
    defaults:
        _controller: CJIMayFlyBundle:Post:add

CJ_IMayFly_edit:
    path:   /edit/{id}
    defaults:
        _controller: CJIMayFlyBundle:Post:edit
    requirements:
        id: \d+

CJ_IMayFly_delete:
    path:   /delete/{id}
    defaults:
        _controller: CJIMayFlyBundle:Post:delete
    requirements:
        id: \d+

CJ_IMayFly_user:
    path:   /user/{id}/{page}
    defaults:
        _controller: CJIMayFlyBundle:Post:user
        page: 1
    requirements:
        id: \d+
        page: \d+

CJ_IMayFly_terms:
    path:   /terms
    defaults:
        _controller: CJIMayFlyBundle:Post:terms

CJ_IMayFly_admin:
    path: /admin
    defaults:
        _controller: CJIMayFlyBundle:Admin:index

CJ_IMayFly_admindelete:
    path: /admin/delete/{id}
    defaults:
        _controller: CJIMayFlyBundle:Admin:delete
    requirements:
        id: \d+