CJ_IMayFly_home:
    path:   /{page}
    defaults:
        _controller: CJIMayFlyBundle:Post:index
        page: 1
    requirements:
        page: \d+


CJ_IMayFly_view:
    path:   /post/{id}
    defaults:
        _controller: CJIMayFlyBundle:Post:view
        id: 1
    requirements:
        id: \d+

CJ_IMayFly_add:
    path:   /add
    defaults:
        _controller: CJIMayFlyBundle:Post:add

CJ_IMayFly_edit:
    path:   /edit/{id}
    defaults:
        _controller: CJIMayFlyBundle:Post:edit
    requirements:
        id: \d+

CJ_IMayFly_delete:
    path:   /delete/{id}
    defaults:
        _controller: CJIMayFlyBundle:Post:delete
    requirements:
        id: \d+

CJ_IMayFly_user:
    path:   /user/{id}/{page}
    defaults:
        _controller: CJIMayFlyBundle:Post:user
        page: 1
    requirements:
        id: \d+
        page: \d+

CJ_IMayFly_terms:
    path:   /terms
    defaults:
        _controller: CJIMayFlyBundle:Post:terms

CJ_IMayFly_search:
    path:   /search/{page}
    defaults:
        _controller: CJIMayFlyBundle:Post:search
        page: 1
    requirements:
        page: \d+

CJ_IMayFly_admin:
    path: /admin/{page}
    defaults:
        _controller: CJIMayFlyBundle:Admin:index
        page: 1
    requirements:
        page: \d+

CJ_IMayFly_adminpostdelete:
    path: /admin/postdelete/{id}
    defaults:
        _controller: CJIMayFlyBundle:Admin:deletePost
    requirements:
        id: \d+

CJ_IMayFly_adminuserdelete:
    path: /admin/userdelete/{id}
    defaults:
        _controller: CJIMayFlyBundle:Admin:deleteUser
    requirements:
        id: \d+

CJ_IMayFly_adminsearch:
    path:   /admin/search/{page}
    defaults:
        _controller: CJIMayFlyBundle:Admin:search
        page: 1
    requirements:
        page: \d+